apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kafka/kafka.yaml
  - kafka/kafka-service.yml
  - zookeper/zk-cs.yml
  - zookeper/zk-hs.yml
  - zookeper/zk-pdb.yml
  - zookeper/zk.yml
  - data-producer.yml
  - ksqldb/ksqldb-service.yml
  - ksqldb/ksqldb.yml

helmCharts:
  - name: kafka-ui
    releaseName: kafka-ui
    repo: https://provectus.github.io/kafka-ui
    valuesFile: kafka/monitor-values.yml