DROP STREAM IF EXISTS geo_data;
CREATE OR REPLACE STREAM geo_data (
    TMPSTAMP VARCHAR,
    ID VARCHAR,
    SENSOR_ID INT,
    COPPER DOUBLE,
    GOLD DOUBLE,
    TOTAL DOUBLE
)
  WITH (kafka_topic='geo_data',VALUE_FORMAT='JSON');